/* eslint-disable react-hooks/purity */
import { Container, Eyebrow } from "@/components/ui";
import { requireAdmin } from "@/lib/portal/auth";
import { readDb } from "@/lib/portal/store";
import { stepMeta } from "@/lib/portal/types";

export const dynamic = "force-dynamic";
export const metadata = { title: "Admin — Digital Builders" };
export default async function AdminPage() {
  await requireAdmin();
  const db = await readDb();
  return <section className="pt-36 pb-20"><Container><Eyebrow>Admin</Eyebrow><h1 className="mt-5 font-display text-4xl font-semibold text-fg">Client portal tracker</h1><div className="mt-8 overflow-x-auto rounded-2xl border border-line"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-surface/70 text-fg"><tr><th className="p-3">Business</th><th>Source</th><th>Plan</th><th>Progress</th><th>Status</th><th>Days</th><th>Last activity</th><th>Actions</th></tr></thead><tbody>{db.clients.map(c=>{const steps=db.steps.filter(s=>s.client_id===c.id); const complete=steps.filter(s=>s.state==='complete').length; const last=steps.map(s=>s.updated_at).sort().at(-1)||c.created_at; const days=Math.floor((Date.now()-new Date(c.created_at).getTime())/864e5); return <tr key={c.id} className="border-t border-line text-fg-muted"><td className="p-3"><strong className="text-fg">{c.business_name}</strong><br />{c.contact_name} · {c.email}</td><td>{c.source}</td><td>{c.plan}</td><td>{complete}/{stepMeta.length}</td><td>{c.status}</td><td>{days}</td><td>{new Date(last).toLocaleDateString('en-CA')}</td><td className="p-3"><form action="/api/admin/client" method="post" className="flex flex-wrap gap-2"><input type="hidden" name="client_id" value={c.id} /><input type="hidden" name="email" value={c.email} /><select name="status" defaultValue={c.status} className="rounded-lg border border-line bg-ink px-2 py-1"><option>paid</option><option>in_progress</option><option>ready_to_build</option><option>building</option><option>in_review</option><option>revising</option><option>live</option><option>suspended</option></select><button name="action" value="status" className="rounded-full border border-line px-3 py-1">Set</button><button name="action" value="resend" className="rounded-full border border-line px-3 py-1">Resend link</button>{c.build_package_path && <a className="rounded-full border border-line px-3 py-1" href={`/admin/package/${c.id}`}>Package</a>}</form></td></tr>})}</tbody></table></div><div className="mt-10 card p-6"><h2 className="font-display text-xl font-semibold text-fg">Coupons</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{db.coupons.map(c=><div key={c.code} className="rounded-2xl border border-line p-4"><p className="font-mono text-sm text-fg">{c.code}</p><p className="text-sm text-fg-muted">{c.source} · uses {c.uses}{c.max_uses ? `/${c.max_uses}` : ''}</p><p className="text-xs text-fg-subtle">Expires {new Date(c.expires_at).toLocaleDateString('en-CA')}</p></div>)}</div></div></Container></section>;
}
